import "tailwindcss/tailwind.css";

export const metadata = {
  title: "Trello 2.0 clone",
  description: "Generated by mr Adhil Muhammed",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
